#!/usr/bin/env python3

import csv
import difflib
import sys

categories = set()

with open('_data/alarms.csv') as alarmsf:
    reader = csv.DictReader(alarmsf)
    for row in reader:
        categories.add(row['category'])

for category in categories:
    close = difflib.get_close_matches(category, categories.difference({category}), cutoff=0.9)
    if len(close) > 0:
        print("Potential typo: '{}' is similar to {}".format(category, close), file=sys.stderr)
        sys.exit(1)
